version: '2'

volumes:
  database_data:
    driver: local


services:
  web:
    build: .
    links:
      - mongo
    environment:
      MONGO_URL: 'monogo'
    command: node node_modules/.bin/nodemon --watch web web/server.js

  mongo:
    image: mongo:latest
    container_name: 'ottter-mongo'
    ports:
      - 27017:27017
    volumes:
      - database_data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
